### ISSUE TITLE
Set up web payments and Stripe account (for website)

### ISSUE THREAD

**Issue by esoli** [oxfordglobal/things-to-do#10]

**Comment by esoli** [comment]
Right now this connected to my personal account, which is pretty sketchy and should be changed soon. We need to open a bank account (maybe w HSBC).

**Comment by iggysiggy** [comment]
Cool.  Fun start-up trivia: do you happen to know who their CTO is?

**Comment by esoli** [comment]
NOO WAYY. Greg Fcking Brockman. What a champ.

**Comment by gyodt** [comment]
Whodat?

**Comment by esoli** [comment]
Stripe has been linked to our new HSBC bank account. Website payments will now be processed properly.
