### ISSUE TITLE
Hiring an Accountant

### ISSUE THREAD

**Issue by esoli** [oxfordglobal/things-to-do#12]
I've looked at a few accounting firms, and this one is cheaper than all the ones I've found. I talked to her on the phone today. She was recommended through the Oxford career services. She works from home and runs her company by herself. Let me know what you guys think of all of this.

------
Hi Erfan,
 
It was great to talk to you today and run through some things with you. Please see detailed below the services and pricing that we can offer you, as we discussed during our conversation.
 
1) Produce annual accounts for a Limited company - prices start from £500 and go up to £850 depending on size of company (it sounds like you would be closer to £500 in your first year)
2) Produce a tax return for the company director - prices start from £149 and go up to £250 depending on the complexity of the return (it sounds like you would be closer to £149 in your first year)
3) Set up Corporation Tax and link it all to ShelleyHolt as the agent - £40
4) Set up of Payroll and link it all to ShelleyHolt as the agent - £40
5) Produce payroll for your employees - £5 per employee per payment made (this includes submitting all the forms and providing you with payslips and tax payments to be made to HMRC)

6) Set up VAT - £40 (it sounds like you won't need this in your first year; not required for companies with turnover < 81k)
7) Produce quarterly VAT returns, submit them to HMRC, and advise of payment required - prices start from £75 per quarter and increase, based on volume of transactions, up to £150 on the standard VAT system, which is what you would register for (again, not required until you register for VAT)
 
As stated in our phone call the above fees can be spread across a 12 month period to assist in cash flow and budgeting. I hope this is detailed enough if you require anything else let me know. If you decide to proceed just let me know which services you would require initially and we can put together a terms of engagement.
 
Look forward to hearing from you.
 
Kind regards, 
Lesley

**Comment by iggysiggy** [comment]
Excellent.  Will we need to have payroll set up for summer school teachers (or anyone else), or is that not going to be necessary for now?

**Comment by esoli** [comment]
Yeah each of those would be one-time payment to the teachers, as opposed to a regular 'salary'. In fact I think most of the payments we give in the near future will be like that, ad hoc. So a £5 charge for each (after the initial £40).

**Comment by gyodt** [comment]
Interesting. We could probably treat the teachers as independent contractors given the nature of the work arrangement. This would avoid payroll paperwork and possible additional costs for salary tax and various benefits contributions. It should also not incur GST because the contractors would not be liable as they are likely to be earning less than 80k or whatever the threshold currently is.

**Comment by esoli** [comment]
I'm meeting with the accountant on May 12 to finalise things. Please share any other concerns/ideas you may have by then. I'll talk to her about the process for independent contractors (that Jordan mentioned above). Let me know if anything else comes to mind.

**Comment by gyodt** [comment]
Erf I think that's all for now. Maybe ask if she has any suggestions we
might not have thought of yet in terms of structuring for efficiency and
minimal tax liability and administrative costs.

**Comment by iggysiggy** [comment]
I'm also happy with this.  I think the independent contractors question is a good one, and I might also ask her whether it makes sense to do anything about payroll now or if we should instead wait until we have actually recruited teachers.

**Comment by esoli** [comment]
I met with the accountant yesterday and took notes on everything. I will send out an email to everyone soon.
