### ISSUE TITLE
Review Facebook page content

### ISSUE THREAD

**Issue by iggysiggy** [oxfordglobal/things-to-do#15]
Check images and posts for tone and clarity.  Focus on making what we are doing obvious to page visitors with no background knowledge but who are part of our target audience.

**Comment by iggysiggy** [comment]
I've made a few changes:
* Small updates to the "about" text and the text on the DevelopMUNt event page
* Made it so that others cannot post on the page or tag photos on the page.  I think we should undo this later so that we can build a community, but for now, we'd just attract awkward questions and spam.
* Swapped out our catchy short description ("The world is too big...") for one that plainly lays out what we do.  This is the only information from the about section that appears above the fold on the timeline, so it should be doing the explaining.

I would also like to diversify the cover and profile photos, but I don't have any good ideas for that yet, and I am not unhappy with what is there now.

**Comment by esoli** [comment]
I added a google doc with the summer school facebook event description that Jordan wrote so we can all share our thoughts before creating the event. I think we really want to capture the right tone for the summer school when we advertise it on facebook. I'm planning on putting it up on Sunday, so let us know what you guys think by then if you can.
