### ISSUE TITLE
Write company description for homepage

### ISSUE THREAD

**Issue by iggysiggy** [oxfordglobal/things-to-do#3]
This should be short, and clearly state what we do (run conferences and educational programs) and what our core goal/value is for doing it (help students to grow by introducing them to students from other backgrounds).

**Comment by iggysiggy** [comment]
I suggest changing
##### We promote education development through collaborative international initiatives
###### Our expanding network is currently active in eight countries: United States, Canada, United Kingdom, Netherlands, Germany, China, India, Turkey, & Qatar
to
##### Oxford Global is an educational organization with an international focus.
###### We believe that the learning that occurs when students of diverse backgrounds and perspectives collaborate is an indispensable part of a well-rounded education, and aim to provide those opportunities to students within a stimulating environment by organizing conferences, programs, and events.

**Comment by iggysiggy** [comment]
@esoli let me know what you think of the above.  Also, I can't edit the website anymore--is this because you've brought it live or something?  Also also, I probably normally wouldn't @ mention you here, and would instead communicate this via email, but I am trying out the functionality.

**Comment by esoli** [comment]
@iggysiggy you should still have editing access. The website admin domain has now moved to oxfordglobal.squarespace.com/config.

As for the homepage, I really like the second section that you wrote (the paragraph "We believe that the learning..."). I'm not so sold on the first line "Oxford Global is an educational organization with an international focus" since it might be a bit dry.

Also, what are your thoughts on the list of countries in our global network (for now). Someone suggested it recently and I thought it was catchy.

**Comment by iggysiggy** [comment]
Right, I do have access there--I think the issue was that it went from your name to "oxfordglobal."

From having to look up random companies and figure out what they do from their websites, one thing that I notice is how often companies fail to describe what they actually do on their website (e.g., "We build value for our partners with innovative frameworks and strong goals").  I'll try to liven that first sentence up a bit, but I do like having a clear statement of what we do right there.

I dislike the list of countries, because it gives me the impression that we're stretching the facts to seem more substantially international than we are.  We might be proud of that list, but who else is it meant to impress?  When we can state that in a large number (e.g., "Our programs have drawn students from over 60 countries") it will be impressive.  Alternatively, though, we'll eventually want to make a team page, and maybe our countries of origin next to our names would be a cool thing to do for that.

**Comment by esoli** [comment]
Okay great. Glad it's working.

Sounds good. I agree with the fact that we shouldn't be one of those organizations that don't explain what they do properly.

Hm, so is that your only reservation with the list? Perhaps if we changed the description to "Our expanding network *of staff and partners* is currently active in the following countries" you would feel better about it? I don't really feel like it's stretching the facts; we've worked hard to build the network of people that we currently have. It's a product of basically two years of conversations, trips, and conferences, and we're very happy with the group of people we have working on this now. As for who it will impress, won't any potential delegate / summer school applicant get at least some impression from an international list such as that? Alternatively, we might want to consider listing it in the bulleted section on the What We Do page (under the What We've Achieved heading maybe?). I agree that we will eventually want a nice team page instead, and perhaps even a map of pins or something like that,  but we'll probably need a few more people before we can justify that.

**Comment by iggysiggy** [comment]
I'm fine with putting the countries list on /what-we-do.  I don't think it is a big enough deal for the homepage, but it fits well in our about section.

**Comment by iggysiggy** [comment]
How's this:
##### The world is too big for classrooms and textbooks.  We're building a better fit.
###### We believe the learning that occurs when students of diverse backgrounds and perspectives collaborate is an indispensable part of a well-rounded education. Oxford Global aims to provide those learning opportunities to students within a stimulating environment by organizing conferences, programs, and events.

**Comment by esoli** [comment]
Yeah, this looks good. Let's add it.
