### ISSUE TITLE
Design Logo

### ISSUE THREAD

**Issue by iggysiggy** [oxfordglobal/things-to-do#6]
We should mock something up now in Photoshop, and probably refine it later in Illustrator if we can.

**Comment by esoli** [comment]
In addition to a company logo, the Istanbul Uni team has asked if we can design a conference logo. They've suggested something potentially along the lines of the following images:

![sample1](https://cloud.githubusercontent.com/assets/10912466/6676741/199981b0-cc22-11e4-8675-8b5323db4247.jpeg)
![sample2](https://cloud.githubusercontent.com/assets/10912466/6676742/1999c864-cc22-11e4-976a-f4106491c34e.jpeg)

**Comment by iggysiggy** [comment]
Yep--skyline logos are super popular in Turkey.  I'll work on that as well.

**Comment by esoli** [comment]
Sweeet. They've asked us for something for the conference by the 25th

**Comment by iggysiggy** [comment]
I've moved the Istanbul logo to ticket #13.  I'm still working on the company logo, and will put any work I do on that in this ticket.

**Comment by iggysiggy** [comment]
Here's a collection of logo ideas I had.  I can tweak them if anyone has ideas for modifications, and I would expect to change the colors down the road (black was easiest for now, but maybe we'd want to go with Oxford blue?).  We could also use more than one of these (for example, with olive branches when a logo appears alone, and without when it appears as the "O" in "Oxford Global").  The blue swirl one is conceptual--if people like that one, I'd spend more time smoothing it out and making it look nice, but that will take a bunch of time, and I didn't want to do a lot of work on it if we weren't going to use it.

![oxford global logos](https://cloud.githubusercontent.com/assets/10913411/7553101/1a4bea0a-f6af-11e4-8d27-1be30ba5d78b.jpg)
@oxfordglobal/owners

**Comment by esoli** [comment]
Nice! I really like the first and last ones. Maybe we could combine those? A plain G and an O filled with your Oxford horizon. What do you think?

**Comment by esoli** [comment]
We can bring in the olive branches when we're doing something specifically MUN related.

**Comment by gyodt** [comment]
I like the first two and the olive branches. Awesome job!

**Comment by eimsoliman** [comment]
The logos look great. I would also say a combination of the second one and the last one with olive branches

**Comment by iggysiggy** [comment]
Here are more options:
![oxford global logos 2](https://cloud.githubusercontent.com/assets/10913411/7580010/26871e7e-f83b-11e4-99e9-94ccf25df872.jpg)

**Comment by gyodt** [comment]
I like the second one a lot, with the bottom part of the O filled in. I am
not crazy about the olive leaves mixed with the OG, I think it should be
one or the other (maybe depending on context? I like the leaves a lot).

**Comment by esoli** [comment]
Yes! I vote for the second one too. This is really great.
I agree about the leaves not going well with OG. For Model UN purposes, I say we could use just the filled in O with the leaves.

John which designs do you like out of all the ones you've made?

**Comment by iggysiggy** [comment]
I like the skyline ones, and don't really have a preference between the filled in and not filled in versions.  It's pretty clear to me that the not filled in part represents the river, but I'd like to show it to someone who's never been to Oxford to see if he or she recognizes that--if people think it's just a weird edge, then we should discard it.

I like adding the branches for MUN programs only, and I am warming to the idea of having a circle-with-skyline theme (like the Istanbul logo) across the different programs we run.

I'm not a fan of the branches with any of the OG logos, and I think I also prefer the O with skyline versions to the OG with skyline ones--the OG with skyline logos may be a bit too busy.  I might mock up a couple of letterheads to see how these would actually look in context.

Also, what do you guys think about colors?  The obvious choice would be to just have a monochromatic Oxford blue theme, but there is no good reason that that needs to be the case.

**Comment by gyodt** [comment]
I'm down with blue... not sure what other colour we would use

**Comment by esoli** [comment]
I'm okay with both blue and black.
